nextweb/urls.py
from django.contrib import admin
from django.urls import path,include
from techbee.urls import router

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve  #追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('techbee/',include("techbee.urls")),
    path('auth/', include('allauth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('api/',include(router.urls)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]



#from django.conf import settings  # 追加
#from django.conf.urls.static import static # 追加

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techbee/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path("index/",views.index,name="index"),
    path('logout/',views.logout_view,name='logout'),
    path('select/',views.login_select_view,name='loginselect'),
    path('afirieito/<str:introducer>/',views.userregi_view,name='userregi'),
    path('parts/<str:search_kind>/',views.parts_search_view,name='partkind'),
    path('parts/<str:username>/<int:id>/',views.parts_part_view,name='part'),
    path('parts/list/<str:username>/<int:categories_id>/',views.parts_list_view,name='partslist'),
    path('account/<str:username>/<str:kind>/',views.accountkind_view,name='accountkind'),
    path('account/metapost/',views.metapost_view,name='metapost'),
    path('community/',views.community_view,name='community'),
    path('community/<int:id>/',views.community2_view,name='community_event'),
    path('album/<int:id>/',views.album_view,name='album'),
    path('ranking/',views.ranking_view,name='ranking'),
    path('tech/<str:category>/<int:w>/<int:num>/',views.tech_view,name='tech'),
    path('tech/<str:category>/series/<int:num>/',views.tech_series_view,name='techseries'),
    path('footer/<str:category>/',views.footer_view,name='footer'),
    path('touko/',views.touko_view,name='touko'),
    path('edit/<str:username>/<int:id>/',views.toukoedit_view,name='toukoedit'),
    path('edit/series/<str:username>/<int:id>/',views.editcate_view,name='edit_cate'),
    path('editsave/<str:username>/<int:id>/',views.editsave_view,name='editsave'),
    path('delete/',views.delete_cate_view,name='delete_cate'),
    path('deletepart/<str:username>/<int:id>/',views.delete_part_view,name='delete_part'),
    path('',views.technext_view,name='technext'),
    path('paypal/',views.paypal_view,name='paypal'),
    path('complete/',views.paypal_complete_view,name='paypal_complete'),
    path('next/',views.paypal_after_view,name='after'),
    path('story/<str:cate>/',views.tb_view,name='tb'),
    path("ajax/", views.like_ajax_response,name='ajax'),
    path("ajaxf/",views.favorite_ajax_view,name='ajaxf'),
    path("ajaxc/",views.channel_ajax_view,name='ajaxc'),
    path('404/',views.error404_view,name='error404'),
    path('500/',views.my_error_handler,name='error500'),
]

###############################################
#API
from rest_framework import routers
from .views import LikeViewSet, FavoriteViewSet,ChannelViewSet


router = routers.DefaultRouter()
router.register('like', LikeViewSet)
router.register('favorite', FavoriteViewSet)
router.register('channel', ChannelViewSet)

###############################################

techbee/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import cloudinary
from cloudinary.models import CloudinaryField
#import cloudinary.api

# Create your models here.


class user_meta(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    username=models.CharField(max_length=20)
    photo=CloudinaryField('image',null=True, blank=True,default="https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg")
    name=models.CharField(max_length=20,null=True, blank=True,default='')
    plofile=models.TextField(max_length=220,null=True, blank=True,default='')
    point=models.IntegerField(default=0)
    like_point=models.IntegerField(default=100)
    give_like=models.IntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(10)])
    position=models.CharField(max_length=10,blank=True,null=True)
    last_login=models.DateTimeField(default=timezone.datetime.now)


class categories_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    categories=models.CharField(max_length=30)
    img=CloudinaryField('image',null=True, blank=True,default="https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg")
    post_time=models.DateTimeField(default=timezone.datetime.now)


class parts_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    categories=models.ForeignKey(categories_model,on_delete=models.SET_NULL,blank=True,null=True)
    file_name=models.CharField(max_length=30)
    image =CloudinaryField('image', null=True, blank=True,default="https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg")
    codepen=models.TextField(max_length=500,default='',null=True, blank=True)
    text=models.TextField(max_length=3000,default='',null=True, blank=True)
    like_count=models.IntegerField(default=0)
    post_time=models.DateTimeField(default=timezone.datetime.now)

class channel_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    username=models.ForeignKey(User,on_delete=models.CASCADE,related_name='channel_user',blank=True,null=True)
    channel_time=models.DateTimeField(default=timezone.datetime.now)

class like_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    part_id=models.ForeignKey(parts_model,on_delete=models.CASCADE,blank=True,null=True)
    like_time=models.DateTimeField(default=timezone.datetime.now)

class favorite_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    part_id=models.ForeignKey(parts_model,on_delete=models.CASCADE,blank=True,null=True)
    favorite_time=models.DateTimeField(default=timezone.datetime.now)

class afirieito_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    introducer=models.CharField(max_length=20)

class event_model(models.Model):
    img=CloudinaryField('image',null=True, blank=True,default="https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg")
    event_name=models.CharField(max_length=15)
    event_date=models.CharField(max_length=15)
    event_time=models.CharField(max_length=15)
    event_venue=models.CharField(max_length=30)
    event_dis=models.TextField(max_length=140,blank=True,null=True)
    set_event=models.DateTimeField(default=timezone.datetime.now)

class event_img_model(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    event=models.ForeignKey(event_model,on_delete=models.CASCADE)
    img=CloudinaryField('image', blank=True,null=True)

class footer_cat_model(models.Model):
    footer_cat=models.CharField(max_length=20)

    def __str__(self):
        return self.footer_cat

class footer_model(models.Model):
    footer_cat=models.ForeignKey(footer_cat_model,on_delete=models.SET_NULL,blank=True,null=True)
    header=models.CharField(max_length=30)
    img=CloudinaryField('image', null=True, blank=True)
    text=models.TextField(max_length=1000)

    def __str__(self):
        return self.header

class tech_tube_model(models.Model):
    category=models.CharField(max_length=30)
    image =CloudinaryField('image', null=True, blank=True)

    def __str__(self):
        return self.category

class tube_movie_model(models.Model):
    category=models.ForeignKey(tech_tube_model,on_delete=models.SET_NULL,blank=True,null=True)
    title=models.CharField(max_length=30)
    image =CloudinaryField('image', null=True, blank=True)
    text=models.TextField(max_length=2000)
    post_time=models.DateTimeField(default=timezone.datetime.now)

    def __str__(self):
        return self.title

class tech_teaching_model(models.Model):
    category=models.CharField(max_length=30)
    image =CloudinaryField('image', null=True, blank=True)

    def __str__(self):
        return self.category

class teaching_movie_model(models.Model):
    category=models.ForeignKey(tech_teaching_model,on_delete=models.SET_NULL,blank=True,null=True)
    title=models.CharField(max_length=30)
    image =CloudinaryField('image', null=True, blank=True)
    text=models.TextField(max_length=2000)
    post_time=models.DateTimeField(default=timezone.datetime.now)

    def __str__(self):
        return self.title


class bee_cate_model(models.Model):
    category=models.CharField(max_length=6)
    image = CloudinaryField('image', null=True, blank=True)

    def __str__(self):
        return self.category

class bee_story_model(models.Model):
    category=models.ForeignKey(bee_cate_model,on_delete=models.CASCADE)
    title=models.CharField(max_length=12)
    image = CloudinaryField('image', null=True, blank=True)
    name1=models.CharField(max_length=20)
    co1=models.TextField(max_length=30)
    name2=models.CharField(max_length=20)
    co2=models.TextField(max_length=30)
    name3=models.CharField(max_length=20)
    co3=models.TextField(max_length=30)
    post_time=models.DateTimeField(default=timezone.datetime.now)

    def __str__(self):
        return self.title



###################receiver################################

techbee/forms.py
from django import forms
from .models import user_meta

class user_meta_form(forms.ModelForm):
    class Meta:
        model=user_meta
        fields=['username']

class card_form(forms.Form):
    number=forms.CharField(min_length=16,max_length=20,
        widget=forms.TextInput(attrs={
               'placeholder':'数字のみ入力可能です。',
               'pattern':'^[0-9]+$'}))
    cvc=forms.CharField(max_length=3,widget=forms.TextInput(attrs={
           'pattern':'^[0-9]+$'}))
    exp_month=forms.CharField(max_length=2,widget=forms.TextInput(attrs={
           'pattern':'^[0-9]+$'}))
    exp_year=forms.CharField(max_length=4,widget=forms.TextInput(attrs={
           'pattern':'^[0-9]+$'}))


class meta_form(forms.ModelForm):
    class Meta:
        model=user_meta
        fields=['name','photo','plofile']

techbee/templates/techbee/account.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'techbee/css/pagi.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'techbee/css/account.css' %}"/>
<div class="main">
  <div class="sq_box">
    <img class='topPhoto' src={{topPhoto.url}} alt="">
  </div>
  <h1 class='username'>{{username}}</h1>
  <div class="discri">
    <p class='name'>{{name}}</p>
    <p class='plofile'>{{plofile}}</p>
    <div class="p_box">
      <p class='point'>point.{{point}}</p>
      <p class='like_point'>like.{{like_point}}</p>
    </div>
    {% if look == 'userself'%}
    <div class='a_core'>
      <label for="corebox" class='anot'><i class="fas fa-cog core"></i></label>
      <input type="checkbox" id='corebox'>
      <div class="pop">
        <div class="account_pop">
          <label class='batu anot'for="corebox"><i class="fas fa-times core"></i></label>
          <form class="pop_form" action="{% url 'metapost' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name='photo' id="myImage" >
            <label for="myImage" class='filelabel'>
              <i class="fas fa-camera"></i>
              <div class="pv_box">
                <img id="preview" class='a' src="{{topPhoto.url}}">
              </div>
              <div class="maskk"></div>
            </label>
            <label for="nameinput" class='inlabel' >name</label>
            <input class='nameinput'type="text" name="name" id='nameinput' value="{{name}}" maxlength="20" placeholder='半角全角20文字以内'>
            <label class='inlabel'for="textinput">plofile</label>
            <textarea name="plofile" id='textinput' maxlength="220" placeholder="半角全角220文字以内">{{plofile}}</textarea>
            <div class="g_like_box">
              <label class='inlabel'for="give_like">1~10までの数字で一度に送るlike数を入力してください</label>
              <input id='give_like' type='number' name="g_like" value="{{user.user_meta.give_like}}"step="1" min="1" max="10">
            </div>
            <input class='anot postb'type="submit" name="" value="POST">
          </form>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  {% if look == 'another'%}
  <form class="channel_form" action="{% url 'ajaxc' %}" method="POST">
    {% csrf_token %}
    <input class='gost' name='username' value={{username}}></input>
    <button class="anot ctag achannel" {%ifequal channel 1 %}id='channel'{% endifequal %} type='submit'>channel</button>
  </form>
  {% endif %}
</div>
<div class="search sticky">
  {% if look == 'userself'%}
  <div class="kind">
    <a class="tag anot"{% ifequal kind "post" %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'post' %}">post</a>
    <a class="tag anot"{% ifequal kind 'list' %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'list' %}">series</a>
    <a class="tag anot"{% ifequal kind 'favorite' %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'favorite' %}">favorite</a>
    <a class="tag anot"{% ifequal kind 'channel' %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'channel' %}">channel</a>
    <a class="tag anot"{% ifequal kind 'member' %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'member' %}">member</a>
  </div>
  {% else %}
  <div class="kind_another">
    <a class="tag anot"{% ifequal kind "post" %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'post' %}">post</a>
    <a class="tag anot"{% ifequal kind 'list' %}id="currentag"{% endifequal %} href="{% url 'accountkind' username 'list' %}">series</a>
  </div>
  {% endif %}
</div>
{% ifequal kind "post" %}
<div class="post">
  {% for a in page_obj %}
  <div class="post_part">
    <div class="part_cen">
      <a href="{% url 'part' a.user.user_meta.username a.id %}">
        <div class="v_box">
          <img class="main_video" src="{{a.image.url}}" alt="">
        </div>
      </a>
      <div class="d_box">
        <a  href="{% url 'accountkind' a.user.user_meta.username 'post' %}">
          <div class="mini_box">
            <img class='miniphoto'src={{a.user.user_meta.photo.url}} alt="">
          </div>
        </a>
        <a class='file_name' href="{% url 'part' a.user.user_meta.username a.id %}">{{ a.file_name }}</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endifequal %}
{% ifequal kind 'list' %}
<div class="post">
  {% for a in page_obj %}
  <div class="relation_category relation_box">
    <div class="i_box">
      <a class='anot a_box'href="{% url 'partslist' a.user.user_meta.username a.id %}">
        <img class='c_img' src={{a.img.url}} alt="">
        <div class="mask">
          <p>{{ a.parts_model_set.all|length}}</p>
          <p><i class="fas fa-align-justify"></i></p>
        </div>
      </a>
      <a class='anot filename2' href="{% url 'partslist' a.user.user_meta.username a.id %}">{{a.categories}}</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endifequal %}
{% ifequal kind "favorite" %}
<div class="post">
  {% if kind_contents != '' %}
  {% for a in page_obj %}
  <div class="post_part">
    <div class="part_cen">
      <a href="{% url 'part' a.user.user_meta.username a.id %}">
        <div class="v_box">
          <img class="main_video" src="{{a.image.url}}" alt="">
        </div>
      </a>
      <div class="d_box">
        <a  href="{% url 'accountkind' a.user.user_meta.username 'post' %}">
          <div class="mini_box">
            <img class='miniphoto gost2'src={{a.user.user_meta.photo.url}} alt="">
          </div>
        </a>
        <a class='file_name' href="{% url 'part' a.user.user_meta.username a.id %}">{{ a.file_name }}</a>
        <a class="namelike" href="{% url 'accountkind' a.user.user_meta.username 'post' %}">{{ a.user.user_meta.username}}・like.{{ a.like_count }}・{{ a.post_time|date:"Y/m/j H:i"}}</a>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endifequal %}
{% ifequal kind "channel" %}
{% if kind_contents != '' %}
<div class="rank_box10">
  {% for a in page_obj %}
  <div class="rank_user10">
    <a class="photocen10" href="{% url 'accountkind' a.username 'post'%}">
      <div class="up_box">
        <img class='userphoto' src={{a.photo.url}} alt="">
      </div>
    </a>
    <a class="anot username2" href="{% url 'accountkind' a.username 'post'%}">{{a.username}}</a>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endifequal %}
{% ifequal kind "member" %}
<div class="post">
  <div class="qrdis">
    <div class="qrd">
      <p>お友達にTechNextをご紹介される際は、以下のurlをコピーしてお友達に転送してください。</p>
      <button onclick = "copy()" class='url_button'>
        <input id="copy_url" type="text" value="https://shielded-gorge-23393.herokuapp.com/techbee/afirieito/{{username}}" readonly>
        <div class="copy_a" id='copy_a'>copy?</div>
      </button>
    </div>
  </div>
  <div class="member_box">
    {% for m in page_obj %}
    <div class="mem">
      <a href="{% url 'accountkind' m.username 'post' %}" class='anot memimg'>
        <div class="mp_box">
          <img src="{{ m.photo.url }}" class='memberphoto' alt="">
        </div>
      </a>
      <div class="memd">
        <a href="{% url 'accountkind' m.username 'post' %}" class='anot membername'>{{m.username}}</a>
        <p>{{m.plofile}}</p>
        <p class='status'>status</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endifequal %}
<div class="pagination">
  <div class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1" class='p_a'><i class="fas fa-fast-backward"></i></a>
          <a href="?page={{ page_obj.previous_page_number }}" class='p_b'><i class="fas fa-step-backward"></i></a>
      {% endif %}

      <span class="current">
          {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class='p_c'><i class="fas fa-step-forward"></i></a>
          <a href="?page={{ page_obj.paginator.num_pages }}" class='p_d'><i class="fas fa-fast-forward"></i></a>
      {% endif %}
  </div>
</div>
<div id="id_div_ajax_response"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script>
  $(".channel_form").submit( function(event) {
      event.preventDefault();
      var form = $(this);
      $.ajax({
        url: "{% url 'ajaxc' %}",
        method: form.prop("method"),
        data: form.serialize(),
        timeout: 10000,
        dataType: "text",
      })
      .done( function(data) {
        $("#id_div_ajax_response").text(data);
        if (data == '登録完了'){
          $('.achannel').addClass('channel');
          $('.id_div_ajax_response_box').removeAttr('id');
        }else{
          $('.achannel').removeClass("channel");
          $('.achannel').removeAttr('id');
        }
      })
    });
</script>
<script type="text/javascript">
  $('#myImage').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
        $('#preview').removeClass("a");
        $('#preview').removeClass("b");

    }
    reader.readAsDataURL(e.target.files[0]);
});

</script>
<script>
  function copy() {
    var text = document.getElementById("copy_url");
    text.select();
    document.execCommand("copy");
    document.getElementById("copy_a").innerHTML = "copy!!";
    }
</script>
{% endblock %}

techbee/templates/techbee/after.html
{% extends "base.html" %}
{% block body %}
<h1>メンバー登録が完了しました！</h1>
<p>TechNextと共に成長していきましょう。</p>
<a href="{% url 'index' %}">Let's Technext</a>
{% endblock %}

techbee/templates/techbee/community.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'techbee/css/community.css' %}"/>
<h1 class='title'>community</h1>
<div class="event_box">
  {% for e in page_obj %}
  <a href="{% url 'community_event' e.id %}" class='notdeco'>
    <div class="event">
      <div class="in_box">
        <img class='event_img' src={{e.img.url}} alt="">
      </div>
      <div class="grid_e_box">
        <p class='event_name'><i class="far fa-bookmark padd"></i>{{e.event_name}}</p>
        <p class='event_date'><i class="far fa-calendar-alt padd"></i>{{e.event_date}}</p>
        <p class='event_time'><i class="far fa-clock pa"></i>{{e.event_time}}</p>
        <p class='event_venue'><i class="far fa-compass pa"></i>{{e.event_venue}}</p>
      </div>
      <p class='event_dis'>{{e.event_dis}}</p>
    </div>
  </a>
  {% endfor %}
</div>
<div class="pagination">
  <div class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1" class='p_a'><i class="fas fa-fast-backward"></i></a>
          <a href="?page={{ page_obj.previous_page_number }}" class='p_b'><i class="fas fa-step-backward"></i></a>
      {% endif %}

      <span class="current">
          {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class='p_c'><i class="fas fa-step-forward"></i></a>
          <a href="?page={{ page_obj.paginator.num_pages }}" class='p_d'><i class="fas fa-fast-forward"></i></a>
      {% endif %}
  </div>
</div>
{% endblock %}

techbee/templates/techbee/footer.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'techbee/css/footer.css' %}"/>
<div class="f_main">
  <h1 class='title'>{{ category }}</h1>
  {% for f in f_cate %}
  <div class="t_box">
    <div class="h_box">
      <h2>{{ f.header }}</h2>
    </div>
    {% if f.img != None %}
    <div class="f_img_box">
      <img src="{{f.img.url}}" alt="">
    </div>
    {% endif %}
    <div class="para_box">
      <p>{{ f.text}}</p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

techbee/templates/techbee/statusveri.html
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>決済が完了していません</h1>
    <p>{{p}}</p>
    <a href="{% url 'userregi' a.introducer %}">戻る</a>
  </body>
</html>

techbee/templates/techbee/tech.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'techbee/css/tech.css' %}"/>
<h1 class='title'>{{t_title}}</h1>
<div class="t_main_box">
  <div class="t_m_box">
    <div class="t_movie">
      <video class="t_main_movie"src={{top.video.url}} poster={{top.image.url}} type="video/mp4" preload="none" controls></video>
    </div>
  </div>
  <h2>{{top.title}}</h2>
  <p>{{top.text}}</p>
</div>
{% if category_len >= 1 %}
<div class="relation">
{% if category_f != '' %}
  <div class="category_f relation_box">
    <div class="i_box">
      <a class='anot a_box' href="{% url 'tech' category w category_f.id %}">
        <img class='c_img'src={{category_f.image.url}} alt="">
        <div class="maskleft"><i class="fas fa-angle-left"></i></div>
      </a>
      <a class='anot filename2'href="{% url 'tech' category w category_f.id %}">{{category_f.title}}</a>
      <p class=minicate>{{category_f.category.category}}</p>
    </div>
  </div>
{% endif%}
  <div class="relation_category relation_box">
    <div class="i_box">
      <a class='anot a_box'href="{% url 'techseries' category top.category.id%}">
        <img class='c_img' src={{top.category.image.url}} alt="">
        <div class="mask">
          <p>{{category_len}}</p>
          <p><i class="fas fa-align-justify"></i></p>
        </div>
      </a>
      <a class='anot filename2' href="{% url 'techseries' category top.category.id%}">{{top.category.category}}</a>
    </div>
  </div>
{% if category_l != '' %}
  <div class="category_l relation_box">
    <div class="i_box">
      <a class='anot a_box' href="{% url 'tech' category w category_l.id %}">
        <img class='c_img' src={{category_l.image.url}} alt="">
        <div class="maskright"><i class="fas fa-angle-right"></i></div>
      </a>
      <a class='anot filename2'href="{% url 'tech' category w category_l.id %}">{{category_l.title}}</a>
      <p class='minicate'>{{category_l.category.category}}</p>
    </div>
  </div>
{% endif %}
</div>
{% endif %}
<div class="sub_box">
  <div class="which_box">
    <div class="w_post anot" {% ifequal w 0%}id='currentw'{%endifequal%}>
      <a href="{% url 'tech' category 0 0 %}">post</a>
    </div>
    <div class="w_post anot"{% ifequal w 1%}id='currentw'{%endifequal%}>
      <a href="{% url 'tech' category 1 0 %}">series</a>
    </div>
  </div>
  <div class="obj_box">
    {%ifequal w 0 %}
    {% for a in page_obj %}
    <div class="obj">
      <a href="{% url 'tech' category 0 a.id%}">
        <div class="t_img_box">
          <img src="{{a.image.url}}" alt="">
        </div>
        <p>{{a.title}}</p>
        <p>{{a.category.category}}</p>
      </a>
    </div>
    {% endfor %}
    {% else %}
    {% for a in page_obj %}
    <div class="obj">
      <a href="{% url 'techseries' category a.id %}">
        <div class="t_img_box">
          <img src="{{a.image.url}}" alt="">
          <div class="mask">
            {% ifequal category 'movie' %}
            <p>{{a.tube_movie_model_set.all|length}}</p>
            {%else%}
            <p>{{a.teaching_movie_model_set.all|length}}</p>
            {%endifequal%}
            <p><i class="fas fa-align-justify"></i></p>
          </div>
        </div>
        <p>{{a.category}}</p>
      </a>
    </div>
    {% endfor %}
    {% endifequal %}
  </div>
  <div class="pagination">
    <div class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1" class='p_a'><i class="fas fa-fast-backward"></i></a>
            <a href="?page={{ page_obj.previous_page_number }}" class='p_b'><i class="fas fa-step-backward"></i></a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class='p_c'><i class="fas fa-step-forward"></i></a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class='p_d'><i class="fas fa-fast-forward"></i></a>
        {% endif %}
    </div>
  </div>
</div>

{% endblock %}